### PR TITLE
Support new hyprland socket location

### PR DESCRIPTION
**Pull request by yavko**

### CODE REVIEW

**Comment by yavko** [comment]
I will merge only if someone informs me it works with both versions

**Comment by AThePeanut4** [comment]
@yavko Can confirm this fixes the issue on the latest Hyprland git version, but it is no longer working on the latest Hyprland release (v0.39.1).

Looking at the changes, I believe this is because it's checking for the existence of `$XDG_RUNTIME_DIR`, which will exist on most Linux systems irrespective of which Hyprland version is being used. What it should instead do is build the entire `$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE` path, and check whether _that_ exists. And then do the same thing for `/run/user/$UID` and `/tmp`.

**Comment by yavko** [comment]
That's funny because I actually had written a working version and then I listened to @outfoxxed who told me to switch them 😭

**Comment by yavko** [comment]
I'll update the code when I get home

**Comment by outfoxxed** [comment]
> That's funny because I actually had written a working version and then I listened to @outfoxxed who told me to switch them 😭

Don't blame misreading what I wrote on me

**Comment by shiro** [comment]
Confirmed working with `hyprland-git 0.39.1.r115.70ebc3ad-1`, thanks for the quick fix :+1:

**Comment by yavko** [comment]
can someone please test new commit, thanks

**Comment by ErrorNoInternet** [comment]
Still works for me on old Hyprland (few commits before the XDG_RUNTIME_DIR change).

**Comment by yavko** [comment]
sick now i need confirmation it works on latest

**Comment by AThePeanut4** [comment]
@yavko Can confirm working on both latest and on v0.39.1, although it won't work if you first run latest and then an older version without logging out, because the `$XDG_RUNTIME_DIR/hypr` directory that it's checking for won't be removed.

Whether that's an edge case worth caring about is up to you, Waybar has the same issue as well.

**Comment by yavko** [comment]
> @yavko Can confirm working on both latest and on v0.39.1, although it won't work if you first run latest and then an older version without logging out, because the `$XDG_RUNTIME_DIR/hypr` directory that it's checking for won't be removed.
> 
> Whether that's an edge case worth caring about is up to you, Waybar's fix has the same issue as well.

New commit should've fixed the edge case

**Comment by yavko** [comment]
Oof build errors, this is why you don't write code on your phone lmao

**Comment by yavko** [comment]
If you could test the edge case again that'd be sick

**Comment by AThePeanut4** [comment]
@yavko Can confirm the edge case issue is no longer happening, works great on both Hyprland versions. Thanks for the fix :+1:

**Comment by fiskhest** [comment]
@yavko Can we get a new tagged build please?

**Comment by yavko** [comment]
> @yavko Can we get a new tagged build please?

Alpha release probably tomorrow, I'm sorry if I don't get to it. It will be an alpha, as there are a ton of breaking changes, and I don't want to fully release 0.4 yet

**Pull request merged**
